/**
 * Dvts API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface AddSystemGroupRequest {
    /**
     * Gets or sets the DisplayName property
     */
    displayName?: string;
    /**
     * Gets or sets the Name property
     */
    name: string;
}
