/**
 * Dvts API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserResponse {
    userAccountId?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    knownAs?: string;
    username?: string;
    contactNumber?: string;
    systemProfileId?: number;
    acceptedTerms?: boolean;
    systemProfile?: string;
    systemFunctions?: Array<number>;
    result?: Array<UserResponse>;
}
