/**
 * Dvts API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AddSystemFunctionRequest } from '../model/addSystemFunctionRequest';
import { AddSystemGroupRequest } from '../model/addSystemGroupRequest';
import { LinkSystemProfileFunctionRequest } from '../model/linkSystemProfileFunctionRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SystemFunctionService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiSystemFunctionAddSystemFunctionGroupPost(request?: AddSystemGroupRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiSystemFunctionAddSystemFunctionGroupPost(request?: AddSystemGroupRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiSystemFunctionAddSystemFunctionGroupPost(request?: AddSystemGroupRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiSystemFunctionAddSystemFunctionGroupPost(request?: AddSystemGroupRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/SystemFunction/AddSystemFunctionGroup`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param request Add System Function Request
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiSystemFunctionAddSystemFunctionPost(request?: AddSystemFunctionRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiSystemFunctionAddSystemFunctionPost(request?: AddSystemFunctionRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiSystemFunctionAddSystemFunctionPost(request?: AddSystemFunctionRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiSystemFunctionAddSystemFunctionPost(request?: AddSystemFunctionRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/SystemFunction/AddSystemFunction`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param request Link System Function to Profile
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiSystemFunctionAddSystemProfileFunctionLinkPost(request?: LinkSystemProfileFunctionRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiSystemFunctionAddSystemProfileFunctionLinkPost(request?: LinkSystemProfileFunctionRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiSystemFunctionAddSystemProfileFunctionLinkPost(request?: LinkSystemProfileFunctionRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiSystemFunctionAddSystemProfileFunctionLinkPost(request?: LinkSystemProfileFunctionRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/SystemFunction/AddSystemProfileFunctionLink`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiSystemFunctionGetSystemFunctionGroupsGet(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiSystemFunctionGetSystemFunctionGroupsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiSystemFunctionGetSystemFunctionGroupsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiSystemFunctionGetSystemFunctionGroupsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/SystemFunction/GetSystemFunctionGroups`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
